spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/sg_security?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
    redis:
        host: 127.0.0.1
        port: 6379
        database: 0
        